[project]
src = "src"
out = "out"
dot_env = ".env"
 
 [networks.eth-forked]
 forked = true
 url = "$MAINNET_RPC_URL"
 default_account_name = "anvil"
 unsafe_password_file = "$ANVIL1_PASSWORD_FILE"
# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
